### ISSUE TITLE
start_wash_cycle function

### ISSUE THREAD

**Issue by ZWael** [mskilab-org/dryclean#34]
Hello, 
First, I would like to congratulate the mskilab team on the outstanding scientific article on plasma tumor burden monitoring
I was trying the MRD tutorial in fact the `run-dryclean.r` script is using the `start_wash_cycle` function that wasn't loaded within library,
I looked for `start_wash_cycle` in the dryclean github repo but wasn't able to find it 

Any help would be appreciated

**Comment by jrafailov** [comment]
Hi, 

Thanks for the inquiry and our apologies for the delayed response! 

We recently updated `dryclean` to follow an R6/object-oriented paradigm and the master branch reflects these changes. We suggest adapting your code to follow the new framework, but if that proves difficult, please feel free to use the `zc_dev` branch as the internal algorithm has remained the same.

The `zc_dev` branch will have the `start_wash_cycle` function immediately accessible when loading the library.
