### ISSUE TITLE
 non-conformable arguments

### ISSUE THREAD

**Issue by ucsfpan** [mskilab-org/dryclean#36]
Hi, Thank you very much for providing the tools. I am currently utilizing dryclean for processing my Whole Genome Sequencing (WGS) data. I have tested the tool with both test and real data sets, and the test data processed successfully.
However, I've encountered an issue during the final step when working with actual data. The process does not complete as expected, and I'm unsure how to resolve this problem.  
My command line :
library(GenomicRanges)
library(gUtils)
library(dryclean)
library(dplyr)
normal_vector_example = readRDS("normal_vector.rds") 
pon_object = pon$new(
    create_new_pon = TRUE, 
    normal_vector = normal_vector_example
    )		
coverage_file = readRDS("tumor_0001_T_fragcount/cov.rds")
coverage_file

dryclean_object <- dryclean$new(pon = pon_object)

dryclean_object$clean(cov = "tumor_0001_T_fragcount/cov.rds",center = TRUE)

Here are the details of the issue:

> dryclean_object$clean(cov = "tumor_0001_T_fragcount/cov.rds",center = TRUE)
Loading coverage
Loading PON a.k.a detergent
WARNING: Input tumor bin size = 200bp. PON bin size = 1000bp. Rebinning tumor to bin size of PON...
Processed 3036315 groups out of 3036315. 100% done. Time elapsed: 12s. ETA: 0s.
Let's begin, this is whole exome/genome
mean-centering the sample
Initializing wash cycle
Using the detergent provided to start washing
lambdas calculated
Error in U.hat %*% sqrt(diag(sigma.hat)) : non-conformable arguments

**Comment by jrafailov** [comment]
Were you able to create the PON successfully? When you load in the pon with dryclean$new and then `str()` the object, do you see values enumerated in the public fields of the PON?

**Comment by jrafailov** [comment]
closing issue see #37
