### ISSUE TITLE
non-numeric argument to mathematical function

### ISSUE THREAD

**Issue by ucsfpan** [mskilab-org/dryclean#37]
Hi auther, I have tried remove na and non-zero values in  reads.corrected for both tumor and normal samples and the error still goes like this:

WARNING: Input tumor bin size = 200bp. PON bin size = 1000bp. Rebinning tumor to bin size of PON...
Processed 2817339 groups out of 2817339. 100% done. Time elapsed: 5s. ETA: 0s.
Let's begin, this is whole exome/genome
Applying the provided mask to the coverage
Processed 2818055 groups out of 2818055. 100% done. Time elapsed: 4s. ETA: 0s.
Processed 2818055 groups out of 2818055. 100% done. Time elapsed: 4s. ETA: 0s.
mean-centering the sample
Initializing wash cycle
Using the detergent provided to start washing
Error in sqrt(m) : non-numeric argument to mathematical function

**Comment by jrafailov** [comment]
Hi @ucsfpan, apologies for the small delay in response here.

It seems likely that the number of bins contained in your input tumor GRanges is not equal to the number of bins contained in the panel of normals (PON). The warning message you are getting indicates the tumor sample will be rebinned to 1kbp to match the PON, but that resultant rebinning isn't yielding the correct number of bins. Dryclean will be robust to 0 and NA values in your input GRanges. 

Are you using fragcounter upstream of this to enumerate reads?

**Comment by ucsfpan** [comment]
Hi @jrafailov, thanks so much for your help. The test data for chr21 is successful. 
My full command is
conda activate fragCounter 
export PATH=${PATH}:$(Rscript -e 'cat(paste0(installed.packages()["fragCounter", "LibPath"], "/fragCounter/extdata/"))')
export GCPATH=~/miniconda3/envs/R-430/lib/R/library/fragCounter/extdata

frag -b BAM/tumor1_T.bam -d $GCPATH/gcmap.19/ -w 1000 -o tumor1_T_fragcount_1000
frag -b BAM/normal1_N.bam -d $GCPATH/gcmap.19/ -w 1000 -o normal1_N_fragcount_1000
## I also try -w 200 and it also fails


## run dryclean
export PATH=${PATH}:$(Rscript -e 'cat(paste0(installed.packages()["dryclean", "LibPath"], "/dryclean/extdata/"))')
drcln -h ## to see the help message

## run  dryclean
library(GenomicRanges)
library(gUtils)
library(dryclean)
library(dplyr)

normal_vector_example <- c("normal1_N_fragcount_1000/cov.rds")
normal_vector_example

"normal1_N_fragcount_1000/cov.rds"

 
pon_object = pon$new(
  create_new_pon = TRUE, 
  normal_vector = normal_vector_example
  )
  
pon_object
<pon>
  Public:
    clone: function (deep = FALSE) 
    get_err: function () 
    get_history: function () 
    get_inf_germ: function () 
    get_k: function () 
    get_L: function () 
    get_S: function () 
    get_seqlengths: function () 
    get_sigma_hat: function () 
    get_template: function () 
    get_U_hat: function () 
    get_V_hat: function () 
    initialize: function (normal_vector = c(), pon_path = NULL, create_new_pon = FALSE, 
  Private:
    err: 0.642531271510563 0.287429125323835 0.223530126763018 0. ...
    history: data.table, data.frame
    inf.germ: NULL
    k: 59
    L: 0.0531264053642663 0.0531264053643618 0.0531264053650999 ...
    normal.table: NULL
    pon.path: NULL
    prepare_pon: function (save_pon, use.all, choose.randomly, choose.by.clustering, 
    S: 0 0 0 0 0 0 0 0 0 0 0.000522218201634228 -0.023099333021 ...
    sigma.hat: 23723.4886259775 7971.47177832048 2950.48347178851 1691. ...
    template: NULL
    U.hat: 1.95389708311056e-05 1.95389708310822e-05 1.953897083104 ...
    V.hat: 0.0374764171992922 0.0622481005374032 0.0166004828642469 ...




coverage_file = readRDS("tumor1_T_fragcount_1000/cov.rds")
> coverage_file
GRanges object with 3095689 ranges and 4 metadata columns:
            seqnames            ranges strand |     reads        gc       map
               <Rle>         <IRanges>  <Rle> | <numeric> <numeric> <numeric>
        [1]        1            1-1000      * |         0         0         0
        [2]        1         1001-2000      * |         0         0         0
        [3]        1         2001-3000      * |         0         0         0
        [4]        1         3001-4000      * |         0         0         0
        [5]        1         4001-5000      * |         0         0         0
        ...      ...               ...    ... .       ...       ...       ...
  [3095685]        Y 59369001-59370000      * |         0         0         0
  [3095686]        Y 59370001-59371000      * |         0         0         0
  [3095687]        Y 59371001-59372000      * |         0         0         0
  [3095688]        Y 59372001-59373000      * |         0         0         0
  [3095689]        Y 59373001-59373566      * |         0         0         0

dryclean_object <- dryclean$new(pon = pon_object)
> dryclean_object
<dryclean>
  Public:
    clean: function (cov, center = TRUE, centering = "mean", cbs = FALSE, 
    clone: function (deep = FALSE) 
    get_history: function () 
    get_mismatch: function () 
    initialize: function (pon) 
  Private:
    dt_mismatch: NULL
    history: data.table, data.frame
    pon: pon, R6

dryclean_object$clean(cov = "tumor1_T_fragcounter/cov.rds",)

## error
> dryclean_object$clean(cov = "tumor1_T_fragcount_1000/cov.rds")
Loading coverage
Loading PON a.k.a detergent
Let's begin, this is whole exome/genome
Applying the provided mask to the coverage
Processed 3036315 groups out of 3036315. 100% done. Time elapsed: 5s. ETA: 0s.
Processed 3036315 groups out of 3036315. 100% done. Time elapsed: 5s. ETA: 0s.
mean-centering the sample
Initializing wash cycle
Using the detergent provided to start washing
Error in sqrt(m) : non-numeric argument to mathematical function

**Comment by jrafailov** [comment]
@ucsfpan very curious.. not exactly sure what the issue is as we haven't seen this exact error before. Your input GRanges has the expected number of bins (3095689). 

Can we follow up via email? my contact is jrafailov at nygenome.org. if you send a single sample input GRanges you're working with, I think that would help me robustly debug the issue here.

**Comment by jrafailov** [comment]
@ucsfpan Thank you for the email and sharing the sample data.

Just attempted to run with your outputs and I was able to reproduce your error. It seems that when I run with the mask, the sample fails; without the mask, it passes. We will adjust our code so this doesn't happen but for now please run as follows. Also, please run with field = "reads". We have showed that dryclean can remove both GC and mappability biases and that raw reads should be fed in, as the PON is composed of raw reads.

```
pon_object <- pon$new(pon_path = ... )
dryclean_object <- dryclean$new(pon = pon_object)
dryclean_object$clean(coverage_path,
                      field = "reads",
                      use.blacklist = F)
```

**Comment by ucsfpan** [comment]
Hi @jrafailov<https://github.com/jrafailov>,  Thanks so much. I would be grateful for any additional insights you could provide about the 'mask' concept. Does it mean  fixed.detergent.rds<https://mskilab-pipeline.s3.amazonaws.com/dryclean/pon/hg19/fixed.detergent.rds>?. Also I  tried the code you suggested, and I'm still facing issues.


I have tried using :
> pon_object <- pon$new(pon_path = "normal1_N_fragcount_1000/cov.rds")
Loading PON...
= F)
                                PON loaded
> dryclean_object <- dryclean$new(pon = pon_object)
> dryclean_object$clean("tumor1_T_fragcount_1000/cov.rds",
+                       field = "reads",
+                       use.blacklist = F)
Loading coverage
Loading PON a.k.a detergent
Error in if (tumor.binsize != pon.binsize & testing == FALSE) { :
  argument is of length zero


or :

> pon_object = pon$new(
+     create_new_pon = TRUE,
+     normal_vector = normal_vector_example
+     )
Loading PON...

> dryclean_object <- dryclean$new(pon = pon_object)
> dryclean_object$clean("tumor1_T_fragcount_1000/cov.rds",
+                       field = "reads",
+                       use.blacklist = F)
Loading coverage
Loading PON a.k.a detergent
Let's begin, this is whole exome/genome
mean-centering the sample
Initializing wash cycle
Using the detergent provided to start washing
lambdas calculated
error :

Error in U.hat %*% sqrt(diag(sigma.hat)) : non-conformable arguments
________________________________
发件人: Johnathan Rafailov ***@***.***>
发送时间: 2024年12月12日 12:56
收件人: mskilab-org/dryclean ***@***.***>
抄送: Pan, Hui ***@***.***>; Mention ***@***.***>
主题: Re: [mskilab-org/dryclean] non-numeric argument to mathematical function (Issue #37)

@ ucsfpan Thank you for the email and sharing the sample data. Just attempted to run with your outputs and I was able to reproduce your error. It seems that when I run with the mask, the sample fails; without the mask, it passes. We will adjust
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@ucsfpan<https://urldefense.com/v3/__https://github.com/ucsfpan__;!!LQC6Cpwp!tqVqIUb99wIl4cTCNCOcxjkocRorX7yLXg3N2IROEYzfs_Eat1gwYOg0waX_9glGyu33ifTb5CnTpBsOPHls5Q8Z$> Thank you for the email and sharing the sample data.

Just attempted to run with your outputs and I was able to reproduce your error. It seems that when I run with the mask, the sample fails; without the mask, it passes. We will adjust our code so this doesn't happen but for now please run as follows. Also, please run with field = "reads". We have showed that dryclean can remove both GC and mappability biases and that raw reads should be fed in, as the PON is composed of raw reads.

pon_object <- pon$new(pon_path = ... )
dryclean_object <- dryclean$new(pon = pon_object)
dryclean_object$clean(coverage_path,
                      field = "reads",
                      use.blacklist = F)

**Comment by jrafailov** [comment]
The following code is incorrect: `pon_object <- pon$new(pon_path = "normal1_N_fragcount_1000/cov.rds")`. The path here should be that of the panel of normals (the "detergent" .rds file you attach above).

The mask refers to a set of regions we apply to WGS that includes pericentric, acrocentric, and psuedoautosomal regions of the genome + others with presumably non-unique sequences. Our group has previously robustly evaluated the alignment of all 150 and 101-mers of the reference genome to the reference genome itself to determine mappability scores and the mask we provide. (it is in extdata as blacklist_A.rds!) As there is high variance/noise in these regions because of poor mappability, robust PCA can not adequately discern the foreground from the PON.

**Comment by ucsfpan** [comment]
Hi @jrafailov,   I have made the changes to the protocol you suggested, and  everything is now working as expected. Thank you very much for your support. Have a nice day!
Best regards,
Hui
________________________________
发件人: Johnathan Rafailov ***@***.***>
发送时间: 2024年12月12日 13:59
收件人: mskilab-org/dryclean ***@***.***>
抄送: Pan, Hui ***@***.***>; Mention ***@***.***>
主题: Re: [mskilab-org/dryclean] non-numeric argument to mathematical function (Issue #37)

The following code is incorrect: pon_object <- pon$new(pon_path = "normal1_N_fragcount_1000/cov. rds"). The path here should be that of the panel of normals (the "detergent" .rds file you attach above). The mask refers to a set of regions
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

The following code is incorrect: pon_object <- pon$new(pon_path = "normal1_N_fragcount_1000/cov.rds"). The path here should be that of the panel of normals (the "detergent" .rds file you attach above).

The mask refers to a set of regions we apply to WGS that includes pericentric, acrocentric, and psuedoautosomal regions of the genome + others with presumably non-unique sequences. Our group has previously robustly evaluated the alignment of all 150 and 101-mers of the reference genome to the reference genome itself to determine mappability scores and the mask we provide. (it is in extdata as blacklist_A.rds!) As there is high variance/noise in these regions because of poor mappability, robust PCA can not adequately discern the foreground from the PON.

**Comment by jrafailov** [comment]
fantastic, happy to hear. happy holidays!
